[dispatcher]
id = "dispatcher"
local_udp_forwarding = true

[metrics]
prometheus = "[127.0.0.1]:30441"

[features]

[api]
addr = "[127.0.0.1]:31141"

[dispatcher.service_addresses]
"1-ff00:0:110,CS" = "10.0.0.68:31000"
"1-ff00:0:110,DS" = "10.0.0.68:31000"
"1-ff00:0:120,CS" = "10.0.0.92:31008"
"1-ff00:0:120,DS" = "10.0.0.92:31008"
"1-ff00:0:130,CS" = "10.0.0.123:31016"
"1-ff00:0:130,DS" = "10.0.0.123:31016"
"1-ff00:0:111,CS" = "10.0.0.76:31022"
"1-ff00:0:111,DS" = "10.0.0.76:31022"
"1-ff00:0:112,CS" = "10.0.0.83:31030"
"1-ff00:0:112,DS" = "10.0.0.83:31030"
"1-ff00:0:121,CS" = "10.0.0.101:31036"
"1-ff00:0:121,DS" = "10.0.0.101:31036"
"1-ff00:0:122,CS" = "10.0.0.115:31046"
"1-ff00:0:122,DS" = "10.0.0.115:31046"
"1-ff00:0:131,CS" = "10.0.0.132:31052"
"1-ff00:0:131,DS" = "10.0.0.132:31052"
"1-ff00:0:132,CS" = "10.0.0.139:31060"
"1-ff00:0:132,DS" = "10.0.0.139:31060"
"1-ff00:0:133,CS" = "10.0.0.147:31066"
"1-ff00:0:133,DS" = "10.0.0.147:31066"
"2-ff00:0:210,CS" = "10.0.0.165:31072"
"2-ff00:0:210,DS" = "10.0.0.165:31072"
"2-ff00:0:220,CS" = "10.0.0.197:31082"
"2-ff00:0:220,DS" = "10.0.0.197:31082"
"2-ff00:0:211,CS" = "10.0.0.154:31092"
"2-ff00:0:211,DS" = "10.0.0.154:31092"
"2-ff00:0:212,CS" = "10.0.0.179:31096"
"2-ff00:0:212,DS" = "10.0.0.179:31096"
"2-ff00:0:221,CS" = "10.0.0.188:31102"
"2-ff00:0:221,DS" = "10.0.0.188:31102"
"2-ff00:0:222,CS" = "10.0.0.211:31110"
"2-ff00:0:222,DS" = "10.0.0.211:31110"

[log.console]
level = "debug"
